/**
 * Arabic wording for the screens, keyed by the exact English text. The interface translator swaps these in when the
 * user chooses Arabic; anything not listed here stays in English. Add entries as screens are used.
 */
export const UI_AR: Record<string, string> = {
  // Menu
  Home: "الرئيسية",
  Sales: "المبيعات",
  Purchases: "المشتريات",
  Accounts: "الحسابات",
  Books: "الدفاتر",
  "Sale invoices": "فواتير المبيعات",
  "Payments in": "المقبوضات",
  Quotations: "عروض الأسعار",
  "Sales orders": "أوامر البيع",
  "Delivery challans": "إشعارات التسليم",
  "Sale returns": "مردودات المبيعات",
  "Purchase bills": "فواتير المشتريات",
  "Payments out": "المدفوعات",
  "Purchase orders": "أوامر الشراء",
  "Purchase returns": "مردودات المشتريات",
  Parties: "العملاء والموردون",
  "Items & stock": "الأصناف والمخزون",
  Expenses: "المصروفات",
  "Other income": "إيرادات أخرى",
  "Cash & bank": "النقد والبنك",
  Reports: "التقارير",
  Settings: "الإعدادات",
  Accounting: "المحاسبة",
  "Deleted entries": "المحذوفات",
  "Service reminders": "تذكيرات الصيانة",
  "Billing & accounts": "الفواتير والحسابات",
  "+ Sale": "+ مبيعات",
  "+ Purchase": "+ مشتريات",
  "☰ Menu": "☰ القائمة",
  "Sign out": "تسجيل الخروج",
  "Sign in": "تسجيل الدخول",
  "My password & sign-in": "كلمة المرور وتسجيل الدخول",
  "My account": "حسابي",
  "Manage companies…": "إدارة الشركات…",
  "Your companies": "شركاتك",
  "Search parties, items, bill numbers…  (Ctrl+K)": "ابحث عن عميل أو صنف أو رقم فاتورة…",
  // Common words
  Cancel: "إلغاء",
  Save: "حفظ",
  "Save changes": "حفظ التغييرات",
  "Save & new": "حفظ وجديد",
  Saving: "جارٍ الحفظ",
  "Saving…": "جارٍ الحفظ…",
  "Saved.": "تم الحفظ.",
  Edit: "تعديل",
  Delete: "حذف",
  Add: "إضافة",
  Remove: "إزالة",
  Back: "رجوع",
  Done: "تم",
  Yes: "نعم",
  No: "لا",
  All: "الكل",
  None: "لا شيء",
  Open: "فتح",
  Close: "إغلاق",
  Print: "طباعة",
  Export: "تصدير",
  Excel: "إكسل",
  Download: "تنزيل",
  Search: "بحث",
  Status: "الحالة",
  Active: "نشط",
  Inactive: "غير نشط",
  Cancelled: "ملغاة",
  Paid: "مدفوعة",
  Unpaid: "غير مدفوعة",
  Overdue: "متأخرة",
  "Partly paid": "مدفوعة جزئياً",
  Date: "التاريخ",
  Name: "الاسم",
  Type: "النوع",
  Total: "الإجمالي",
  Item: "الصنف",
  Items: "الأصناف",
  Party: "العميل / المورد",
  Customer: "عميل",
  Customers: "العملاء",
  Supplier: "مورد",
  Suppliers: "الموردون",
  Everyone: "الجميع",
  Balance: "الرصيد",
  Amount: "المبلغ",
  Quantity: "الكمية",
  Qty: "الكمية",
  Rate: "السعر",
  Tax: "الضريبة",
  Discount: "الخصم",
  Description: "الوصف",
  Details: "التفاصيل",
  Notes: "ملاحظات",
  Phone: "الهاتف",
  Email: "البريد الإلكتروني",
  Address: "العنوان",
  City: "المدينة",
  Country: "الدولة",
  Category: "التصنيف",
  Categories: "التصنيفات",
  Group: "المجموعة",
  Unit: "الوحدة",
  Units: "الوحدات",
  Code: "الرمز",
  Number: "الرقم",
  Account: "الحساب",
  Entry: "القيد",
  When: "متى",
  From: "من",
  To: "إلى",
  As: "حتى",
  "As of": "حتى تاريخ",
  Debit: "مدين",
  Credit: "دائن",
  Profit: "الربح",
  Cost: "التكلفة",
  Margin: "الهامش",
  Stock: "المخزون",
  Value: "القيمة",
  Company: "الشركة",
  Companies: "الشركات",
  Users: "المستخدمون",
  Role: "الدور",
  Password: "كلمة المرور",
  "Not set": "غير محدد",
  Optional: "اختياري",
  History: "السجل",
  Actions: "الإجراءات",
  Message: "الرسالة",
  Messages: "الرسائل",
  // Buttons and page titles
  "Add party": "إضافة عميل / مورد",
  "+ Add party": "+ إضافة عميل / مورد",
  "Add item": "إضافة صنف",
  "+ Add item": "+ إضافة صنف",
  "Add user": "إضافة مستخدم",
  "+ Add user": "+ إضافة مستخدم",
  "+ Add company": "+ إضافة شركة",
  "+ Add account": "+ إضافة حساب",
  "+ Add asset": "+ إضافة أصل",
  "+ New entry": "+ قيد جديد",
  "+ New role": "+ دور جديد",
  "Add expense": "إضافة مصروف",
  "Add bank account": "إضافة حساب بنكي",
  "Receive payment": "استلام دفعة",
  "Make payment": "سداد دفعة",
  "New sale invoice": "فاتورة بيع جديدة",
  "Import from Excel": "استيراد من إكسل",
  "Import / bulk update": "استيراد / تحديث جماعي",
  "Export to Excel": "تصدير إلى إكسل",
  "Download template": "تنزيل النموذج",
  "Download PDF": "تنزيل PDF",
  "Print / PDF": "طباعة / PDF",
  Receipt: "إيصال",
  "Send to customer": "إرسال للعميل",
  "Copy link": "نسخ الرابط",
  "Record": "تسجيل",
  "Check file": "فحص الملف",
  "Back up now": "نسخ احتياطي الآن",
  Restore: "استعادة",
  "Set up your business": "إعداد نشاطك التجاري",
  "Business settings": "إعدادات النشاط",
  "This company": "هذه الشركة",
  Business: "النشاط",
  "Roles & access": "الأدوار والصلاحيات",
  "Tax rates": "معدلات الضريبة",
  "Price lists": "قوائم الأسعار",
  "Item fields": "حقول الأصناف",
  Billing: "الفوترة",
  "Billing preferences": "تفضيلات الفوترة",
  "Activity log": "سجل النشاط",
  Backups: "النسخ الاحتياطية",
  "Chart of accounts": "دليل الحسابات",
  "Journal entries": "قيود اليومية",
  "Trial balance": "ميزان المراجعة",
  "Balance sheet": "الميزانية العمومية",
  "Fixed assets": "الأصول الثابتة",
  "Profit & loss": "الأرباح والخسائر",
  "Day book": "دفتر اليومية",
  "Stock summary": "ملخص المخزون",
  "Low stock": "مخزون منخفض",
  "Tax report": "تقرير الضريبة",
  "TCS and TDS": "TCS و TDS",
  "Item-wise sales": "المبيعات حسب الصنف",
  "Item-wise purchases": "المشتريات حسب الصنف",
  "Batches and expiry": "الدفعات وتواريخ الانتهاء",
  "Serial numbers": "الأرقام التسلسلية",
  "Profit on bills and parties": "الربح حسب الفاتورة والعميل",
  "Bill-wise": "حسب الفاتورة",
  "Party-wise": "حسب العميل",
  // Dashboard and lists
  "To receive": "مستحق لنا",
  "To pay": "مستحق علينا",
  "To receive from customers": "مستحق من العملاء",
  "To pay suppliers": "مستحق للموردين",
  "Cash & bank balance": "رصيد النقد والبنك",
  "Invoices this month": "فواتير هذا الشهر",
  "Low stock items": "أصناف منخفضة المخزون",
  "This month": "هذا الشهر",
  "Sales and purchases, last 12 months": "المبيعات والمشتريات آخر 12 شهراً",
  "Payments received": "المدفوعات المستلمة",
  "Payments made": "المدفوعات المسددة",
  "Overdue invoices": "فواتير متأخرة",
  "No overdue invoices.": "لا توجد فواتير متأخرة.",
  "See all": "عرض الكل",
  "Last entry": "آخر حركة",
  "Sale price": "سعر البيع",
  "Purchase price": "سعر الشراء",
  "Stock value": "قيمة المخزون",
  "Stock value (at cost)": "قيمة المخزون (بالتكلفة)",
  "Items shown": "الأصناف المعروضة",
  "Opening balance": "الرصيد الافتتاحي",
  "Closing balance": "الرصيد الختامي",
  "Balance due": "المتبقي",
  "Due date": "تاريخ الاستحقاق",
  "Payment mode": "طريقة الدفع",
  "Bill to": "فاتورة إلى",
  "Cash bill": "فاتورة نقدية",
  "Sold for (before tax)": "سعر البيع (قبل الضريبة)",
  "Cost of goods": "تكلفة البضاعة",
  "Taxable value": "القيمة الخاضعة للضريبة",
  Cess: "رسوم إضافية",
  "Round off": "تقريب",
  "Amount before tax": "المبلغ قبل الضريبة",
  "Discount given": "الخصم الممنوح",
  "Total tax": "إجمالي الضريبة",
  "Business name": "اسم النشاط",
  "Legal name": "الاسم القانوني",
  "State (optional)": "المنطقة (اختياري)",
  "Billing address": "عنوان الفاتورة",
  "Shipping address": "عنوان الشحن",
  "Address and contact": "العنوان والتواصل",
  "Bank details for invoices": "البيانات المصرفية للفواتير",
  "Bank name": "اسم البنك",
  "Account number": "رقم الحساب",
  Branch: "الفرع",
  Invoice: "فاتورة",
  Bill: "الفاتورة",
  "Bill date": "تاريخ الفاتورة",
  "Opening stock": "المخزون الافتتاحي",
  "Item code": "رمز الصنف",
  "Item categories": "تصنيفات الأصناف",
  "Expense categories": "تصنيفات المصروفات",
  "Other-income categories": "تصنيفات الإيرادات الأخرى",
  "New category": "تصنيف جديد",
  Rename: "إعادة تسمية",
  // Settings and admin
  "Email (used to sign in)": "البريد الإلكتروني (لتسجيل الدخول)",
  "Temporary password": "كلمة مرور مؤقتة",
  "New password": "كلمة المرور الجديدة",
  "New password again": "أعد كتابة كلمة المرور الجديدة",
  "Change password": "تغيير كلمة المرور",
  "Companies this person can open": "الشركات المسموح لهذا المستخدم بفتحها",
  "Owners can open every company.": "المالكون يفتحون جميع الشركات.",
  Owner: "المالك",
  Accountant: "المحاسب",
  "Billing staff": "موظف الفواتير",
  "Role name": "اسم الدور",
  "Short description": "وصف مختصر",
  "Bills and entries": "الفواتير والقيود",
  "Fields this role can see": "الحقول التي يراها هذا الدور",
  Administration: "الإدارة",
  "Show in dropdowns": "إظهار في القوائم",
  "Show in item dropdowns": "إظهار في قوائم الأصناف",
  "In use": "قيد الاستخدام",
  Connections: "الاتصالات",
  "Recent messages": "آخر الرسائل",
  "Alerts to you": "تنبيهات لك",
  "Messages to customers": "رسائل للعملاء",
  "Invoice language": "لغة الفاتورة",
  "Invoice style": "شكل الفاتورة",
  "Accent colour": "لون التمييز",
  Paper: "الورق",
  "On bills": "على الفواتير",
  "On printed invoices": "على الفواتير المطبوعة",
  "Bill number prefixes": "بادئات أرقام الفواتير",
  Logo: "الشعار",
  Signature: "التوقيع",
  Upload: "رفع",
  Replace: "استبدال",
  "Arabic only": "العربية فقط",
  "English only": "الإنجليزية فقط",
  "English and Arabic": "الإنجليزية والعربية",
  "Nightly snapshot": "النسخة الليلية",
  "Last test restore": "آخر اختبار استعادة",
  "Your requests": "طلباتك",
  // Accounting
  Assets: "الأصول",
  Liabilities: "الالتزامات",
  Equity: "حقوق الملكية",
  Income: "الإيرادات",
  Asset: "أصل",
  Depreciation: "الإهلاك",
  "Book value": "القيمة الدفترية",
  "Written off": "المهلك",
  Bought: "تاريخ الشراء",
  "Journal entry": "قيد يومية",
  Narration: "البيان",
  "Post entry": "ترحيل القيد",
  "+ Add line": "+ إضافة سطر",
  Balanced: "متوازن",
  // Sign in / setup
  "Email address": "البريد الإلكتروني",
  "Sign in to your account": "سجّل الدخول إلى حسابك",
  "Two-step code": "رمز التحقق",
  // Empty states
  "Nothing in this period": "لا شيء في هذه الفترة",
  "No entries yet": "لا توجد قيود بعد",
  "No parties yet": "لا يوجد عملاء أو موردون بعد",
  "No products yet": "لا توجد أصناف بعد",
  "Nothing has been deleted": "لم يُحذف شيء",
  "None yet.": "لا شيء بعد.",
  "No services coming up": "لا توجد صيانة قادمة",
};

/** Words used to detect that the visible page is already Arabic, so it isn't translated twice. */
export const hasArabicScript = (s: string) => /[؀-ۿ]/.test(s);
